### 포켓몬 검색

### Server Chat (InferenceEngine -> Ollama)
POST http://localhost:8080/test/chat
Content-Type: application/json

{
  "q": "The user pours toxins into the target by wrapping them in a toxic, corrosive chain. This may also leave the target badly poisoned."
}


### Stream test (POST + body)
POST http://localhost:8080/test/chat/stream
Accept: text/event-stream
Content-Type: application/json; charset=utf-8

{
  "q": "The user pours toxins into the target by wrapping them in a toxic, corrosive chain. This may also leave the target badly poisoned.",
  "flushWords": 10
}